name: LaunchPads-OG
version: '${version}'
main: net.trueog.launchpadsog.LaunchPadsOG
api-version: '${apiVersion}'
commands:
  launchpad:
    usage: /launchpad
permissions:
  launchpad.cangive:
    default: op
  launchpad.canreload:
    default: op
  launchpad.canset:
    default: op
  launchpad.canbreak:
    default: op
  launchpad.candelete:
    default: op